esphome:
  name: zehnder
  friendly_name: Zehnder

esp32:
  board: esp32dev

# Enable Home Assistant API
api:
  encryption:
    key: !secret YOUR_API_KEY

# WLAN Konfiguration
wifi:
  ssid: YOUR_SSID
  password: !secret YOUR_PASSWORD
  use_address: zehnder
  fast_connect: true
  power_save_mode: none

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Zehnder Fallback Hotspot"
    password: "14sX32Tm8k0e"

captive_portal:

# OTA Updates
ota:
  - platform: esphome
    password: !secret YOUR_ESPHOME_PASSWORD

# Logger
logger:
  level: DEBUG
  baud_rate: 0  # Wichtig: deaktiviert ESPHome-Log über UART, damit UART frei ist!

# Serieller Anschluss zur ComfoAir
uart:
  id: uart_comfoair
  tx_pin: GPIO17
  rx_pin: GPIO16
  baud_rate: 9600
  stop_bits: 1
  parity: NONE

# ComfoAir Custom Component
external_components:
  - source:
      type: local
      path: ./components

comfoair_bridge:
  id: comfoair_bridge1

sensor:
  - platform: template
    name: "Zuluft Temperatur"
    id: comfoair_supply_temp
    unit_of_measurement: "°C"
    accuracy_decimals: 1

  - platform: template
    name: "Abluft Temperatur"
    id: comfoair_exhaust_temp
    unit_of_measurement: "°C"
    accuracy_decimals: 1

  - platform: template
    name: "Außenluft Temperatur"
    id: comfoair_fresh_temp
    unit_of_measurement: "°C"
    accuracy_decimals: 1

  - platform: template
    name: "Fortluft Temperatur"
    id: comfoair_return_temp
    unit_of_measurement: "°C"
    accuracy_decimals: 1

binary_sensor:
  - platform: template
    name: "Bypass aktiv"
    id: comfoair_bypass_active

  - platform: template
    name: "Filterstatus"
    id: comfoair_filter_ok

switch:
  - platform: template
    name: "Bypass Override"
    id: comfoair_bypass_override
    turn_on_action:
      - lambda: 'id(comfoair_bridge1).set_bypass(true);'
    turn_off_action:
      - lambda: 'id(comfoair_bridge1).set_bypass(false);'

  - platform: template
    name: "Lüftung Ein/Aus"
    id: comfoair_power
    turn_on_action:
      - lambda: 'id(comfoair_bridge1).set_power(true);'
    turn_off_action:
      - lambda: 'id(comfoair_bridge1).set_power(false);'

number:
  - platform: template
    name: "Lüfterstufe"
    id: comfoair_fan_speed
    min_value: 1
    max_value: 4
    step: 1
    set_action:
      - lambda: 'id(comfoair_bridge1).set_fan_speed(x);'
